addon/components/ilios-calendar-event-month.js
addon/components/ilios-calendar-event.js
addon/templates/components/ilios-calendar-day.hbs
addon/templates/components/ilios-calendar-month.hbs
addon/templates/components/ilios-calendar-week.hbs
addon/templates/components/ilios-calendar.hbs

Solves popover display issue for ILMs.
@jrjohnson @saschaben Please review.
Issue: [#883](https://github.com/ilios/frontend/issues/883)

updated calendar popover display for ILM

---

addon/components/ilios-calendar-day.js
addon/components/ilios-calendar-event.js
addon/templates/components/ilios-calendar-event.hbs

Fix class for ilios-calendar-day which allows the day view to scroll.
I’m proved ILMs so they show up with a Due: and the dueByDate instead of start and end times
which don’t matter.  I cheated and didn’t translate “Due” we can deal
with that later.

Display Fixes

---

addon/templates/components/ilios-calendar-single-event-objective-list.hbs
addon/templates/components/ilios-calendar-single-event.hbs

Fixes https://github.com/ilios/frontend/issues/1077

prevented more html escapes

---

addon/components/ilios-calendar-event-month.js
addon/components/ilios-calendar-event.js

When students view scheduled events they don’t have permissions to see any details.  In order to prevent confusion this stops them from clicking on these events and navigating to a single event page that is broken.

Prevent users from clicking on scheduled events

---

addon/templates/components/ilios-calendar-single-event.hbs

This ensures that when they do stack that the session details are on
top.
Refs ilios/frontend#1295

Put session details before course details

---

addon/components/ilios-calendar-multiday-event.js
addon/templates/components/ilios-calendar-multiday-event.hbs
addon/templates/components/ilios-calendar-multiday-events.hbs
app/components/ilios-calendar-multiday-event.js
tests/integration/components/ilios-calendar-multiday-event-test.js

This prevents students with less privileges from accessing the single
event view, which would shown data for a scheduled event.

Remove single event link from scheduled multi-day events

---

addon/components/ilios-calendar-single-event-objective-list.js
addon/components/ilios-calendar-single-event.js
addon/styles/addon.css
addon/styles/addon.scss
addon/templates/components/ilios-calendar-single-event-learningmaterial-list.hbs
addon/templates/components/ilios-calendar-single-event-objective-list.hbs
addon/templates/components/ilios-calendar-single-event.hbs
tests/integration/components/ilios-calendar-single-event-learningmaterial-list-test.js
tests/integration/components/ilios-calendar-single-event-objective-list-test.js
tests/integration/components/ilios-calendar-single-event-test.js

Fixes https://github.com/ilios/frontend/issues/877 
Fixes https://github.com/ilios/frontend/issues/1338
App PR: https://github.com/ilios/frontend/pull/1351
On Proxy:
1) To verify no content phrase occurring when no content is available, `/events/S0120160130O72596`.
2) To verify loading status, `/events/S0120160121O62770`.
3) To verify if `Taught By` phrase is gone when instructors are empty, `/events/S0120160128O73151`.

added no content phrase, loader, tests

---

addon/components/ilios-calendar-event-month.js
addon/components/ilios-calendar-event.js
addon/components/ilios-calendar-multiday-event.js

Ember.computed.any is deprecated and we need to use Ember.computed.or
If tests pass this is good to merge.

Remove deprecated method

---

package.json

Clears up some deprecation issues - no other changes.

Update elemental-calendar to 0.0.8

---

addon/components/ilios-calendar.js
addon/templates/components/ilios-calendar.hbs
tests/dummy/app/controllers/application.js

We were relying on events to be sorted by the API, this ensures that
does not matter.
Events are sorted first by start date, then by duration, then by title.  This matches what MS Outlook seems to do.
Fixes #14

Sort events for the calendar

---

addon/templates/components/ilios-calendar-event-month.hbs
addon/templates/components/ilios-calendar-event.hbs
package.json

Events needed to get a top level element otherwise the tip wasn't
hovering over the event.  Probably because the location gets bounced
around by the style too much.

Use new ember-tooltips method for creating tooltips

---

.gitignore
.travis.yml
README.md
bower.json
config/ember-try.js
config/environment.js
index.js
package.json
tests/dummy/config/environment.js
tests/index.html

I ran the [Project Update](https://github.com/ember-cli/ember-cli/releases/tag/v2.9.0) instructions for the latest Ember CLI release, and the merged, kept or reverted any file changes introduced by `ember init` as applicable.

upgrade to Ember CLI 2.9.0

---

addon/components/ilios-calendar-month.js
addon/components/ilios-calendar.js
addon/styles/addon.scss
addon/templates/components/ilios-calendar-month.hbs
addon/templates/components/ilios-calendar.hbs
package.json
tests/integration/components/ilios-calendar-month-test.js

Instead of trying to fit in all of the events in a day of the month view
just show two.  If there are more than 2 then display 'Show More' which
links to the day view.
Fixes #47

Improve month view by limiting events displayed

---

addon/components/ilios-calendar-day.js
addon/components/ilios-calendar-event-month.js
addon/components/ilios-calendar-event.js
addon/components/ilios-calendar-month.js
addon/components/ilios-calendar-multiday-event.js
addon/components/ilios-calendar-multiday-events.js
addon/components/ilios-calendar-week.js
addon/components/ilios-calendar.js
addon/templates/components/ilios-calendar-day.hbs
addon/templates/components/ilios-calendar-month.hbs
addon/templates/components/ilios-calendar-multiday-event.hbs
addon/templates/components/ilios-calendar-multiday-events.hbs
addon/templates/components/ilios-calendar-week.hbs
addon/templates/components/ilios-calendar.hbs
tests/integration/components/ilios-calendar-day-test.js
tests/integration/components/ilios-calendar-month-test.js
tests/integration/components/ilios-calendar-multiday-event-test.js
tests/integration/components/ilios-calendar-test.js
tests/integration/components/ilios-calendar-week-test.js

Removes a lot of boilerplate and makes it easier to trace the results of
user actions up to their change point.
Fixes #106

Use closure actions across the board

---

addon/styles/addon.scss

Needed to break the relationship of the calendar height and the viewport
so that a month view calendar would scroll instead of compressing the
days.
Fixes #109

Ensure the month calendar days fit and scroll

---

addon/templates/components/ilios-calendar-month.hbs

This isn't a closure action it needs to be quoted.
Fixes #116

Fix changeToDayView action

---

ember-cli-build.js
index.js
package.json

The newest version relies on a beta version of libsass which breaks for
us.  Instead we pin our version and wait for a fix.

Lock our version of node-sass to v4.3.0

---

addon/components/ilios-calendar-event-month.js

Temporary fix. 
Refs ilios/frontend#2504

Hardwired "Taught by" and "Course" Labels in Month View

---

addon/styles/addon.scss
app/styles/app.scss
blueprints/ilios-calendar/index.js
bower.json
ember-cli-build.js
package.json

This no longer requires the bower.json package. Also stopped attempting
to send font-awesome upstream in our scss file.  That becomes the
responsibility of the addon consumer.

Updated to the latest ember-font-awesome

---

addon/components/ilios-calendar-event.js
addon/templates/components/ilios-calendar-event.hbs

Not passing keys to computed properties and having a weird unless / if
syntax was getting our events flagged as infinitely re-rendering event
thought they probably weren't infinite, they certainly were not optimal.

Address infinite re-rendering issues
