ilios/calendar

addon/components/ilios-calendar.js, addon/templates/components/ilios-calendar.hbs, tests/dummy/app/controllers/application.js
When an offering happens a lot of times in the same time block (small
group) we only display it once on the week / month calendar and every
time on the day calendar.
=> Correctly handle small group offerings

addon/components/ilios-calendar.js, addon/styles/addon.css, addon/styles/addon.scss, addon/templates/components/ics-feed.hbs, index.js, tests/integration/components/ics-feed-test.js
Fixes style, removed the refresh button that doesn’t work right now, and fixed the calendar not refreshing when events got changed.
=> Various Improvements

addon/templates/components/ilios-calendar-single-event-learningmaterial-list.hbs
Fixes https://github.com/ilios/frontend/issues/1069
I tested and it works on demo3 proxy `/events/S0120151110O65796`
=> learning material links open in a new window

addon/styles/addon.css, addon/styles/addon.scss, addon/templates/components/ilios-calendar-single-event-learningmaterial-list.hbs
Fixes Issue: https://github.com/ilios/frontend/issues/881
App PR: https://github.com/ilios/frontend/pull/1079
=> added event-page notes

addon/components/ilios-calendar-day.js, addon/components/ilios-calendar-multiday-events.js, addon/components/ilios-calendar-week.js, addon/components/ilios-calendar.js, addon/styles/addon.css, addon/styles/addon.scss, addon/templates/components/ilios-calendar-day.hbs, addon/templates/components/ilios-calendar-multiday-events.hbs, addon/templates/components/ilios-calendar-week.hbs, addon/templates/components/ilios-calendar.hbs, app/components/ilios-calendar-multiday-events.js, tests/dummy/app/controllers/application.js
Pulled multi day events out of the calendar as they break this display.
This is our temporary workaround to fix this issue.
=> Place multi day events in their own place

addon/components/ilios-calendar-event.js, addon/templates/components/ilios-calendar-day.hbs, bower.json, tests/dummy/app/controllers/application.js
Events in the week calendar were getting the day class applied to them.  Now they are displaying and stacking correctly.
=> Fix for week events display

addon/components/ilios-calendar-event.js, addon/styles/addon.css, addon/styles/addon.scss, addon/templates/components/ilios-calendar-event.hbs, tests/dummy/app/controllers/application.js
=> display more info in calendar events

addon/components/ilios-calendar-month.js, addon/components/ilios-calendar-week.js, addon/components/ilios-calendar.js, addon/templates/components/ilios-calendar-month.hbs, addon/templates/components/ilios-calendar-week.hbs, tests/dummy/app/controllers/application.js
=> link multi-event proxies in week/month view to day view

addon/components/ilios-calendar-single-event.js
Defaults to ‘None’ if nothing is passed in
=> Add default noContentPhrase

addon/templates/components/ilios-calendar.hbs
=> switched out icons in calendar nav.

addon/templates/components/ilios-calendar-event.hbs
=> show icon on scheduled events in day/week view as applicable.

addon/components/ilios-calendar-event-month.js, addon/components/ilios-calendar-event.js, addon/components/ilios-calendar.js, addon/templates/components/ilios-calendar-event-month.hbs, addon/templates/components/ilios-calendar-event.hbs, tests/dummy/app/controllers/application.js
=> indicated parallel event placeholders as such

addon/components/ilios-calendar-event-month.js, addon/components/ilios-calendar-event.js, addon/components/ilios-calendar-single-event.js, addon/components/ilios-calendar.js, addon/styles/addon.css, addon/styles/addon.scss, addon/templates/components/ilios-calendar-event-month.hbs, addon/templates/components/ilios-calendar-event.hbs, addon/templates/components/ilios-calendar-single-event.hbs, tests/unit/components/ilios-calendar-event-test.js, tests/unit/components/ilios-calendar-single-event-test.js
Fixes https://github.com/ilios/frontend/issues/1299
Exclamation Icons on (if updated within 5 days or less)...
- Calendar - Day
- Calendar - Week
- Calendar - Month
- Event Page
=> fixed issue #1299

addon/components/ilios-calendar-single-event-learningmaterial-list.js, addon/templates/components/ilios-calendar-single-event-learningmaterial-list.hbs
=> sort learning materials for display in cal event details

addon/styles/addon.css, addon/styles/addon.scss
The read was too angry [ci skip]
=> Update alert icon color

addon/components/ilios-calendar-single-event.js, addon/templates/components/ilios-calendar-single-event.hbs, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/application.hbs, tests/integration/components/ilios-calendar-single-event-test.js
=> Add location to single event

.npmignore, .travis.yml, README.md, bower.json, config/ember-try.js, package.json, testem.js, tests/helpers/module-for-acceptance.js
Update other dependencies as well.
=> Update to ember-cli 2.6.0

addon/templates/components/ilios-calendar-event.hbs, package.json, tests/dummy/app/controllers/application.js
We were using the draft icon scheduled events.
Fixes #87
=> Use draft icon for draft events and clock icon for scheduled ones.

addon/components/ilios-calendar-single-event.js, addon/templates/components/ilios-calendar-single-event.hbs
=> display special attire/equipment required if applicable.

addon/components/ilios-calendar-event-month.js, addon/components/ilios-calendar-event.js, addon/mixins/tooltip-content.js, tests/unit/mixins/tooltip-content-test.js
=> refactored out tooltip content into reusable mixin.

.template-lintrc.js, addon/components/ilios-calendar-event.js, addon/components/ilios-calendar-week.js, addon/templates/components/ics-feed.hbs, addon/templates/components/ilios-calendar-event.hbs, addon/templates/components/ilios-calendar-multiday-events.hbs, addon/templates/components/ilios-calendar-single-event-learningmaterial-list.hbs, addon/templates/components/ilios-calendar-single-event-objective-list.hbs, addon/templates/components/ilios-calendar-single-event.hbs, addon/templates/components/ilios-calendar-week.hbs, package.json, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/application.hbs
I copied the config for template linting from ilios/frontend.
=> Enabled template linting

addon/components/ilios-calendar-single-event-learningmaterial-list.js, addon/components/ilios-calendar-single-event-objective-list.js, addon/templates/components/ilios-calendar-single-event-learningmaterial-list.hbs, addon/templates/components/ilios-calendar-single-event-objective-list.hbs, addon/templates/components/ilios-calendar-single-event.hbs, tests/integration/components/ilios-calendar-single-event-objective-list-test.js, tests/integration/components/ilios-calendar-single-event-test.js
We were expecting to get promises for some of the passed values which
made everything more complicated.  Instead we should take values and
simplify these components.
Fixes #104
=> Take single event values instead of promises

addon/styles/addon.scss
=> Fix ceremony class name

tests/dummy/app/templates/application.hbs
Needed to use new API to pass closure actions.
Fixes #110
=> Fix dummy calendar

config/ember-try.js, ember-cli-build.js
Some leftover jshint references needed to be removed
=> Remove old jshint code

addon/templates/components/ics-feed.hbs, addon/templates/components/ilios-calendar-day.hbs, addon/templates/components/ilios-calendar-multiday-event.hbs, addon/templates/components/ilios-calendar-week.hbs, tests/integration/components/ilios-calendar-multiday-event-test.js
=> correctly wired links in multiday event in list to event details.

addon/templates/components/ics-feed.hbs, addon/templates/components/ilios-calendar-single-event.hbs
=> made minor markup tweaks to appease the linter.

addon/components/ilios-calendar-single-event-learningmaterial-list.js, addon/templates/components/ilios-calendar-single-event-learningmaterial-list.hbs
rely on frontend to pass in sorted LMs.
refs ilios/frontend#2675.
=> remove custom sorting for learning materials.

addon/components/ilios-calendar-single-event.js, addon/templates/components/ilios-calendar-single-event.hbs
Adds an icon and message for events that require attendance
=> Handle attendance required events

addon/components/ilios-calendar-single-event-objective-list.js, addon/components/ilios-calendar-single-event.js, addon/styles/addon.scss, addon/templates/components/ilios-calendar-single-event-objective-list.hbs, addon/templates/components/ilios-calendar-single-event.hbs, tests/dummy/app/controllers/application.js, tests/integration/components/ilios-calendar-single-event-objective-list-test.js
refs ilios/frontend#2747.
the same goes for Session Objectives.
=> Sortable objectives

ember-cli-build.js, index.js, package.json
=> un-pinned node sass version.

.bowerrc, .eslintrc.js, .npmignore, .travis.yml, addon/components/ilios-calendar.js, addon/templates/components/ilios-calendar.hbs, config/ember-try.js, config/environment.js, ember-cli-build.js, index.js, package.json, testem.js, tests/.eslintrc.js, tests/dummy/app/controllers/application.js, tests/dummy/config/environment.js, tests/helpers/start-app.js
Ran `ember init` and updated blueprints as well.
=> Update to ember-cli 2.12.1

addon/components/ilios-calendar-single-event.js, addon/components/ilios-calendar.js, addon/templates/components/ilios-calendar-month.hbs, addon/templates/components/ilios-calendar-week.hbs, tests/unit/components/ilios-calendar-single-event-test.js
Moment can use the current locale to format all of the dates
appropriately.
=> Provide API for setting the locale
